language: node_js
node_js:
  - "8"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://ngravi.com/github-user-timeline/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ng-app
  on:
    branch: master
